# Site settings
title: "Fakhri Zulkifli"
baseurl: ""
url: "https://fakhrizulkifli.github.io"
disqus:

social_media:
  domain: "twitter.com"
  nick: "d0lph1n98"
source_code:
  server: "github.com"
  nick: "fakhrizulkifli"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
