title: Fakhri Zulkifli
name: Fakhri Zulkifli
description: Personal blog.
permalink: /posts/:year/:month/:day/:title/

baseurl: ""
url: "https://fakhrizulkifli.github.io"
lang: "en"

github_username:  fakhrizulkifli

social:
    name: Fakhri Zulkifli
    links:
        - https://twitter.com/d0lph1n98
        - https://github.com/fakhrizulkifli

# Build settings
markdown: kramdown
theme: clean-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
